updated pom to 2.0 liberty maven plugin
mattbsox/sample.javaee7.jsonp pull request #1
Opened 2017-05-15 20:29 UTC by mattbsox

2017-05-15 20:36 UTC, dnwarnock commented
Looks good. There is just some formatting in the pom that could be cleaned up (indentions)

2017-05-25 16:25 UTC, dnwarnock requested changes

2017-05-25 16:25 UTC, dnwarnock commented on pom.xml
> +                    <type>zip</type>
I don't think this configuration does anything

2017-05-26 17:29 UTC, patricktiu approved these changes

2017-05-26 17:37 UTC, merged